### PR TITLE
IT-35636 / Refactor Packaging Plugins into one Plugin

### PR DESCRIPTION
**Pull request by apgsga-jhe**
We'll now have one plugin called "packaging-tasks", the following have been deleted:

- common-service-packager
- it21-gui-packager
- rpm-service-packager
- zip-service-packager

Within the new packaging-tasks, we can probably organize the resources into src/main/resources better, but I believe this can be done within a second step.

Also, probably our integration tests will have to be adapted, but I'm not sure that my branch contains the latest status, because of https://jira.apgsga.ch/browse/IT-35661 . Therefore, I would first merge this one if ok for you, and then do test and adaptions accordingly directly on master (this will be the test for IT-35661) as well.

If OK for you, I'll merge tomorrow morning.

### CODE REVIEW

**Comment by chhex** [comment]
@apgsga-jhe I think you did to much ;-)   I would definitely  keep the rpm, ui, common, zip , service Plugin's as distinct Plugins apart, with the same id different Id's as they had before.  
In the same project and with one jar, yes, but as different Plugins. 
I thinks in terms of tasks it is much clearer that way, you know with tasks are common and with are used for example only for the rpm. Otherwise you get always all tasks. 
Also you break the "api" of the package scripts and the init.d scripts

**Comment by apgsga-jhe** [comment]
@chhex : Ok thanks, yep makes sense, I'll do the chages.

**Comment by apgsga-jhe** [comment]
@chhex : I added again separated plugins, but under the same project, see here: https://github.com/apgsga-it/apg-gradle-plugins/pull/47/commits/ec30cf48e93130e19edf6858d7baf231b55c6c38

If ok for you, I'll merge this one on Tuesday morning ... If everything goes wrong with the integration, I'll at least have some hours to fix it ... Today is already becoming short :(

**Comment by apgsga-jhe** [comment]
> Looks good to me.
> Small thing : In the functional test i prefer the explicit Plugin id , instead of the static reference.
> Ratio: You see what will change in the existing scripts.

Good point, I'll change it before merging.

**Pull request merged**
