### PR TITLE
IT-34974 / Consider LocalRepo same as RemoteRepo

### PR DESCRIPTION
**Pull request by apgsga-jhe**
Tests are running fine locally. Some of them had to be adpated, but this was expected. I believe this is what we want, or at least I hope it went in the right direction ...
In any case, ready for a first review/comment/feedback ...

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe Certainly the way to go. Some comments below, i am not decided on the extent, since i haven't really looked the code in detail.
> The tests against the remote repositories work as before?

@chhex : Yep, they're still OK.

**Comment by apgsga-jhe** [comment]
> > > @apgsga-jhe Certainly the way to go. Some comments below, i am not decided on the extent, since i haven't really looked the code in detail.
> > > The tests against the remote repositories work as before?
> > 
> > 
> > @chhex : Yep, they're still OK.
> 
> @apgsga-jhe Then i would suggest to move on. We can discuss next week, how we what to proceed with the points i mentioned. I do think it could be useful, basically looking for the canonical form to bootstrap externally preconfigured extension object = learning process
> But for now old good. What do you think?

@chhex : Yep sure, we can definitely have a look together next week. In the meantime I'll go through your comment and see what I can already (try) to improve.

**Comment by chhex** [comment]
@apgsga-jhe yep, but since the tests are running and the api stands , we can think to deprioritize this:   create a new issue and  move on to more important issues

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe yep, but since the tests are running and the api stands , we can think to deprioritize this: create a new issue and move on to more important issues

@chhex : ok good point (y) , I'll merge and create a new ticket

**Pull request merged**
