### PR TITLE
IT-35635 Version Resolver use Gradle API for Configuration Actions 

### PR DESCRIPTION
**Pull request by chhex**
Following changes: 

1.  Version Resolver uses Gradle API for Configuration Actions instead of the Task "configureResolutionStrategy"  
2. Moved (temporally) the Digiflex Builds to this repo 

Concerning 1. now 
`./gradlew clean buildRpm deployRpm .......`
instead of 
`./gradlew clean configureResolutionStrategy buildRpm .....`

Concerning 2. : This is for easier Integration and verifying the requirements
Also currently only digiflex-jadas-pkg is aligned with the current state of the Plugins

The interesting changes: 

- integration/digiflex/digiflex-jadas-pkg/build.gradle
- plugins/version-manager/src/main/kotlin/com/apgsga/maven/dm/plugin/VersionResolutionPlugin.kt
- The Task configureResolutionStrategy has been deleted

TODO: 
I will migrate the other ones 

NOTE: 
Maybe we should consider syncing the Idea specific files via iml files?

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
@chhex 
"_Maybe we should consider syncing the Idea specific files via iml files?_" : Yep, good idea!

I obviously didn't go through all new files coming from Digiflex, but had a look at the one you mentioned, and also those where something changed. 

Looking good to me.

Tomorrow I'll probably be ready to submit a pull request for IT-35481 (centralized Users/Pwd). If you want, I can also merge this one tomorrow morning before going forward, just let me know.

**Comment by chhex** [comment]
@apgsga-jhe 
"Tomorrow I'll probably be ready to submit a pull request for IT-35481 (centralized Users/Pwd). If you want, I can also merge this one tomorrow morning before going forward, just let me know."
Great. I am going to do a little more testing.....
If you don't hear through comments here until let's tomorrow morning latest 8:00 , we're good to go. I confirm this further down the line.

**Comment by chhex** [comment]
@apgsga-jhe I think we're good to go for the merge. 
The buildRpm and publish new Bom seem to work for testing-pkg and digiflex-jadas-pkg, but I will continue with Testing and further Integration.  
If you encounter any problems , please shout

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe I think we're good to go for the merge.
> The buildRpm and publish new Bom seem to work for testing-pkg and digiflex-jadas-pkg, but I will continue with Testing and further Integration.
> If you encounter any problems , please shout

@chhex  : Ok cool thanks 👍 . I'll merge.

**Pull request merged**
