### PR TITLE
IT-35566 / Revision Tracking must support Multiservices

### PR DESCRIPTION
**Pull request by apgsga-jhe**
Ready for a review ... As soon as the review is fine, I'll also create additional test cases (I believe we should better cover with additional scenario), maybe I'll create a new ticket for that.
See the modification done for the "VersionResolution.kt" file. I did it just that it compiles, but I believe the "VersionResolution" extension should have a "serviceName" parameter, what do you think?

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe Yep, im terms of API , that's is what i also would have done ;-)

@chhex : Ok cool thanks. I'll merge this one now and will create 2 additional tickets:

1. One for "VersionResolution.kt" which needs to deal with service name
2. One so that we create additional test cases for the "revision-manager"

**Comment by chhex** [comment]
@apgsga-jhe  btw the serviceName comes from the apgPackage extension.
So probably there will be a dependency in com.apgsga.version.resolver to the common packaging plugin, which makes sense since the installTarget is now redundant in both

**Comment by chhex** [comment]
@apgsga-jhe  Hmm i think the one for "VersionResolution.kt" which needs to deal with service name should be merged with branch... otherwise our head will fail

**Comment by chhex** [comment]
@apgsga-jhe You can assign that ticket to me and i ll work on this branch and merge?

**Comment by chhex** [comment]
@apgsga-jhe  Or you , whatever is best for you

**Comment by chhex** [comment]
@apgsga-jhe  But this needs to be done , after https://jira.apgsga.ch/browse/IT-35667 , which i am currently working on.

**Comment by chhex** [comment]
@apgsga-jhe  or i create a branch for https://jira.apgsga.ch/browse/IT-35667

**Comment by apgsga-jhe** [comment]
@chhex  : Ok, I'll assign you https://jira.apgsga.ch/browse/IT-35671

**Pull request merged**
