### PR TITLE
IT-36059 / Using latest version of Piper

### PR DESCRIPTION
**Pull request by apgsga-jhe**
@chhex : A quick one, our plugin should use our latest Piper Version ...

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
If it builds without piper dependency, I'll remove it.

**Comment by apgsga-jhe** [comment]
@chhex  : Regarding this one, we said we could put the piper version in a property, centralized. Well, for our Plugin, at the moment we don't really have that, each plugin sub-project defines its own dependencies with hard-coded version. If for you OK, I would keep it like that for now, and create a new ticket that the depdencies's version should be managed from a central place. ok for you?

**Comment by chhex** [comment]
@apgsga-jhe  Yep , makes sense

**Comment by apgsga-jhe** [comment]
@chhex : ok cool, here we go: https://jira.apgsga.ch/browse/IT-36087
I'll now merge this one.

**Pull request merged**
