### PR TITLE
ARCH-421 : no default maven local repo should be configured

### PR DESCRIPTION
**Pull request by apgsga-jhe**
A local repository will be configured only if  the build.gradle contains the following:

```
repositories {
     maven {
         name = 'local'
     }
}
```

The same applies for publishing into a local maven repository:

```
publishing {
   repositories {
         maven {
              name = 'local'
         }
   } 
} 
```
When define as above, the local maven repository will be read from the settings.xml file configued without our gradle.properties.

BE CAREFUL: the above doesn't deal with the following:
```
repositories {
     mavenLocal()
}
```
If one uses `mavenLocal()`, then the default from Gradle will be applied, as described here : https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:maven_repo

`Gradle uses the same logic as Maven to identify the location of your local Maven cache. If a local repository location is defined in a settings.xml, this location will be used. The settings.xml in USER_HOME/.m2 takes precedence over the settings.xml in M2_HOME/conf. If no settings.xml is available, Gradle uses the default location USER_HOME/.m2/repository.`

Tests have been improved as well so they don't have to be ignored.

### CODE REVIEW

**Comment by chhex** [comment]
@apgsga-jhe  Generell feedback, based on above comments:
Why not tests as precondition if a mavenLocal is configured, respectively exists and then throw an exception. I think everything else is confusing?

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe Generell feedback, based on above comments: Why not tests as precondition if a mavenLocal is configured, respectively exists and then throw an exception. I think everything else is confusing?

@chhex : I didn't think to be that extrem :) , but I like the idea. I'll see to add that (y)
@apgsga-stb : FYI

**Comment by chhex** [comment]
Otherwise  it looks good, it has less code ;-)  although i can't much in this case without seeing the whole context

**Comment by chhex** [comment]
> > @apgsga-jhe Generell feedback, based on above comments: Why not tests as precondition if a mavenLocal is configured, respectively exists and then throw an exception. I think everything else is confusing?
> 
> @chhex : I didn't think to be that extrem :) , but I like the idea. I'll see to add that (y) @apgsga-stb : FYI

Btw , i think, you are lucky and the mavenLocal() will already be there, when the plugin code comes to effect ;-)

**Comment by apgsga-jhe** [comment]
> > > @apgsga-jhe Generell feedback, based on above comments: Why not tests as precondition if a mavenLocal is configured, respectively exists and then throw an exception. I think everything else is confusing?
> > 
> > 
> > @chhex : I didn't think to be that extrem :) , but I like the idea. I'll see to add that (y) @apgsga-stb : FYI
> 
> Btw , i think, you are lucky and the mavenLocal() will already be there, when the plugin code comes to effect ;-)

@chhex : See the last commit, we're now throwing an exception: https://github.com/apgsga-it/apg-gradle-plugins/pull/83/commits/8e69dab4707f39f7671b529ec1ad411658245a63

I didn't test the publish repo because you can't publish to mavenLocal(). If one wants to do so, he'll use the publishToMavenLocal() task, but I don't believe we want to avoid the usage of this task (not even sure it would be feasible).

@apgsga-stb : FYI

**Review by chhex — APPROVED** [review]

**Pull request merged**
