### PR TITLE
IT-35042 / Externalize Service List into Json File in Gradlehome

### PR DESCRIPTION
**Pull request by apgsga-jhe**
Far from beeing perfect, but as written in the ticket, it can at lease serves us as basis for discussion. I wanted to initilize the list using a static helper method, but we need the "project" to get the gradle home folder ... and currently the project is passed to the constructor, which makes it impossible to be used within a static bloc.
Also, with these changes, we have duplicate code with what is beeing done for common-repo (where we also need to ready information from a JSON). I added this in the description of IT-35079. Maybe we can think of having a separated project responsible of the "JSON Peristence"? 
But for now, with the changes done for this pull request, tests are still running fine. Having said that, if ok for you, I would merge it and go forward with the next one ... what do you think?

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe I think the supportedServices shouldn't be exposed anymore as attribute = the services cannot be directly changed anymore via Dsl. What should / can be exposed is the path to the configuration file. This should be helpful for testing.
> 
> Naturally the existing Build using the ApgCommonPackageExtension Dsl would be impacted and would need to change: Digiflex and the Testservice variants. Naturally also the corresponding Jenkins Jobs.
> 
> If we are fairly confident, that this is the way to go, we should do above. And use this solution as proposal to move forward.
> If not, we can discuss first.
> 
> @apgsga-stb FYI

@chhex : Yep agreed, the list of services should excusively be in the configuration file.. I changed it accordingly (still need to ensure tests are running fine), see following commit: https://github.com/apgsga-it/apg-gradle-plugins/pull/12/commits/6e80ca34e99cb2fc9a3b794e0407bb9ef5201eab

Was it what you meant, right?

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe Yep exactly , but the effected functional tests , build (Digiflex , test services) need to be changed accordingly, right?

@chhex ; Yep ;), I just ran a test locally which is now failing (expected). I'll adapt what fails, and let you know when ready.

**Comment by chhex** [comment]
> > @apgsga-jhe Yep exactly , but the effected functional tests , build (Digiflex , test services) need to be changed accordingly, right?
> 
> @chhex ; Yep ;), I just ran a test locally which is now failing (expected). I'll adapt what fails, and let you know when ready.

Also the existing builds using the rpm-service-packager respectively the common-service-packager (Digiflex services and testapp-kotlin-pkg and testapp-pkg

**Comment by apgsga-jhe** [comment]
> > > @apgsga-jhe Yep exactly , but the effected functional tests , build (Digiflex , test services) need to be changed accordingly, right?
> > 
> > 
> > @chhex ; Yep ;), I just ran a test locally which is now failing (expected). I'll adapt what fails, and let you know when ready.
> 
> Evidently: Also the existing builds using the rpm-service-packager respectively the common-service-packager (Digiflex services and testapp-kotlin-pkg and testapp-pkg and the corresponding jenkins jobs.

(y)

**Comment by apgsga-jhe** [comment]
Closing without merging, I'll create a new one from a new basis. After having done a rebase, there ae too many commits to really see what has been updated ;) ...

**Pull request closed without merging**
